name: web3_jsonrpc
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.11.1
  http: 0.13.3
  sha3: ^0.2.0
  ninja: ^3.0.2

dev_dependencies:
  test: ^1.17.10
